### PR TITLE
Update Dockerfile_aarch64_ascend

### PR DESCRIPTION
**Pull request by wangyuanxiong-hub**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
Hi, @wangyuanxiong-hub 
thanks for your contribution
Could you kindly let us know your motivation for this PR?

**Comment by wangyuanxiong-hub** [comment]
Hi! During the process of building docker on the server, I found that these dependencies need to be installed.




---Original---
From: "Lyu ***@***.***&gt;
Date: Thu, Oct 10, 2024 19:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [InternLM/lmdeploy] Update Dockerfile_aarch64_ascend (PR #2578)




 
Hi, @wangyuanxiong-hub
 thanks for your contribution
 Could you kindly let us know your motivation for this PR?

**Comment by wangyuanxiong-hub** [comment]
> Hi, @wangyuanxiong-hub
> 
> > Hi! During the process of building docker on the server, I found that these dependencies need to be installed.
> > […](#)
> > ---Original--- From: "Lyu _**@**_._**> Date: Thu, Oct 10, 2024 19:22 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [InternLM/lmdeploy] Update Dockerfile_aarch64_ascend (PR #2578) Hi, @wangyuanxiong-hub thanks for your contribution Could you kindly let us know your motivation for this PR? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> In our host machine, the dockerfile builds successfully, could you collect your host machine info such as what OS is and the detail error message if not adding setuptools-rust package? thanks

Of course, my system kernel details are as follows：
```shell
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```
The error message is as follows：
```shell
 > [final_builder 3/3] RUN --mount=type=cache,target=/root/.cache/pip     sed -i '/triton/d' requirements/runtime.txt &&     pip3 install -v --no-build-isolation -e .:                                                                                                                                                                 
0.738 Using pip 24.2 from /usr/local/python3.10.5/lib/python3.10/site-packages/pip (python 3.10)                                                                    
0.816 Looking in indexes: http://mirrors.aliyun.com/pypi/simple                                                                                                     
0.816 Obtaining file:///opt/lmdeploy                                                                                                                                
0.818   Preparing metadata (setup.py): started
0.819   Running command python setup.py egg_info
1.108   /usr/local/python3.10.5/lib/python3.10/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
1.108   !!
1.108 
1.108           ********************************************************************************
1.109           Requirements should be satisfied by a PEP 517 installer.
1.109           If you are using pip, you can try `pip install --use-pep517`.
1.109           ********************************************************************************
1.110 
1.110   !!
1.110     dist.fetch_build_eggs(dist.setup_requires)
1.187   running egg_info
1.187   creating /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info
1.194   writing /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/PKG-INFO
1.202   writing dependency_links to /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/dependency_links.txt
1.203   writing entry points to /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/entry_points.txt
1.207   writing requirements to /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/requires.txt
1.207   writing top-level names to /tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/top_level.txt
1.207   writing manifest file '/tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/SOURCES.txt'
1.248   reading manifest file '/tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/SOURCES.txt'
1.249   reading manifest template 'MANIFEST.in'
1.249   warning: no files found matching 'lmdeploy/lib/*.so'
1.249   warning: no files found matching 'lmdeploy/lib/*.so*'
1.249   warning: no files found matching 'lmdeploy/lib/*.dll'
1.250   warning: no files found matching 'lmdeploy/lib/*.pyd'
1.250   warning: no files found matching 'lmdeploy/bin/*'
1.250   adding license file 'LICENSE'
1.255   writing manifest file '/tmp/pip-pip-egg-info-h2300ek2/lmdeploy.egg-info/SOURCES.txt'
1.298   Preparing metadata (setup.py): finished with status 'done'
1.485 Collecting accelerate>=0.29.3 (from lmdeploy==0.6.1)
1.651   Downloading http://mirrors.aliyun.com/pypi/packages/2a/7c/6daed4be624f903643edd1b91670ce321a4cf08afd2b96ac368461742e89/accelerate-1.0.0-py3-none-any.whl (330 kB)
1.776 Collecting einops (from lmdeploy==0.6.1)
1.844   Downloading http://mirrors.aliyun.com/pypi/packages/44/5a/f0b9ad6c0a9017e62d4735daaeb11ba3b6c009d69a26141b258cd37b5588/einops-0.8.0-py3-none-any.whl (43 kB)
2.272 Collecting fastapi (from lmdeploy==0.6.1)
2.328   Downloading http://mirrors.aliyun.com/pypi/packages/06/ab/a1f7eed031aeb1c406a6e9d45ca04bff401c8a25a30dd0e4fd2caae767c3/fastapi-0.115.0-py3-none-any.whl (94 kB)
2.439 Collecting fire (from lmdeploy==0.6.1)
2.440   Using cached fire-0.7.0-py3-none-any.whl
2.514 Collecting mmengine-lite (from lmdeploy==0.6.1)
2.591   Downloading http://mirrors.aliyun.com/pypi/packages/75/84/3b1730bb21d67487c7cfcd175e44920f34b031bb313ad183398ea182535e/mmengine_lite-0.10.5-py3-none-any.whl (452 kB)
2.653 Requirement already satisfied: numpy<2.0.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (1.24.0)
3.037 Collecting openai (from lmdeploy==0.6.1)
3.105   Downloading http://mirrors.aliyun.com/pypi/packages/3d/49/72198d0941b3a0264b6d13033823025c01c497f1cbfd83db310392c49c0e/openai-1.51.2-py3-none-any.whl (383 kB)
3.368 Collecting outlines (from lmdeploy==0.6.1)
3.567   Downloading http://mirrors.aliyun.com/pypi/packages/ee/f9/8cbb60342168adc17ea15f8005c01f12b5ed7d6b6d86bf15d31bb209794f/outlines-0.1.0-py3-none-any.whl (89 kB)
3.660 Collecting peft<=0.11.1 (from lmdeploy==0.6.1)
3.774   Downloading http://mirrors.aliyun.com/pypi/packages/19/99/c5e0292a6d2a62e95c3dfe674ce9e8f8a9fe5d4835d3c9bb9b3e016f02ae/peft-0.11.1-py3-none-any.whl (251 kB)
3.820 Requirement already satisfied: pillow in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (10.4.0)
3.821 Requirement already satisfied: protobuf in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (5.28.2)
4.160 Collecting pydantic>2.0.0 (from lmdeploy==0.6.1)
4.212   Downloading http://mirrors.aliyun.com/pypi/packages/df/e4/ba44652d562cbf0bf320e0f3810206149c8a4e99cdbf66da82e97ab53a15/pydantic-2.9.2-py3-none-any.whl (434 kB)
4.344 Collecting pynvml (from lmdeploy==0.6.1)
4.568   Downloading http://mirrors.aliyun.com/pypi/packages/54/5b/16e50abf152be7f18120f11dfff495014a9eaff7b764626e1656f04ad262/pynvml-11.5.3-py3-none-any.whl (53 kB)
4.617 Requirement already satisfied: safetensors in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (0.4.5)
4.877 Collecting sentencepiece (from lmdeploy==0.6.1)
5.087   Downloading http://mirrors.aliyun.com/pypi/packages/fd/46/316c1ba6c52b97de76aff7b9da678f7afbb52136afb2987c474d95630e65/sentencepiece-0.2.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.3 MB)
5.203      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 11.2 MB/s eta 0:00:00
5.286 Collecting shortuuid (from lmdeploy==0.6.1)
5.359   Downloading http://mirrors.aliyun.com/pypi/packages/c0/44/21d6bf170bf40b41396480d8d49ad640bca3f2b02139cd52aa1e272830a5/shortuuid-1.0.13-py3-none-any.whl (10 kB)
5.527 Collecting tiktoken (from lmdeploy==0.6.1)
5.808   Downloading http://mirrors.aliyun.com/pypi/packages/e9/98/18ec4a8351a6cf4537e40cd6e19a422c10cce1ef00a2fcb716e0a96af58b/tiktoken-0.8.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.1 MB)
5.955      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.1 MB/s eta 0:00:00
5.961 Requirement already satisfied: torch<=2.3.1,>=2.0.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (2.1.0)
5.962 Requirement already satisfied: torchvision<=0.18.1,>=0.15.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (0.16.0)
5.963 Requirement already satisfied: transformers in /usr/local/python3.10.5/lib/python3.10/site-packages (from lmdeploy==0.6.1) (4.45.2)
6.231 Collecting uvicorn (from lmdeploy==0.6.1)
6.410   Downloading http://mirrors.aliyun.com/pypi/packages/3c/55/37407280931038a3f21fa0245d60edeaa76f18419581aa3f4397761c78df/uvicorn-0.31.1-py3-none-any.whl (63 kB)
6.427 Requirement already satisfied: packaging>=20.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from accelerate>=0.29.3->lmdeploy==0.6.1) (24.1)
6.428 Requirement already satisfied: psutil in /usr/local/python3.10.5/lib/python3.10/site-packages (from accelerate>=0.29.3->lmdeploy==0.6.1) (6.0.0)
6.429 Requirement already satisfied: pyyaml in /usr/local/python3.10.5/lib/python3.10/site-packages (from accelerate>=0.29.3->lmdeploy==0.6.1) (6.0.2)
6.430 Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from accelerate>=0.29.3->lmdeploy==0.6.1) (0.25.2)
6.438 Requirement already satisfied: tqdm in /usr/local/python3.10.5/lib/python3.10/site-packages (from peft<=0.11.1->lmdeploy==0.6.1) (4.66.5)
6.519 Collecting annotated-types>=0.6.0 (from pydantic>2.0.0->lmdeploy==0.6.1)
6.596   Downloading http://mirrors.aliyun.com/pypi/packages/78/b6/6307fbef88d9b5ee7421e68d78a9f162e0da4900bc5f5793f6d3d0e34fb8/annotated_types-0.7.0-py3-none-any.whl (13 kB)
8.322 Collecting pydantic-core==2.23.4 (from pydantic>2.0.0->lmdeploy==0.6.1)
8.489   Downloading http://mirrors.aliyun.com/pypi/packages/cc/69/5f945b4416f42ea3f3bc9d2aaec66c76084a6ff4ff27555bf9415ab43189/pydantic_core-2.23.4-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.8 MB)
8.648      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.3 MB/s eta 0:00:00
8.654 Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/python3.10.5/lib/python3.10/site-packages (from pydantic>2.0.0->lmdeploy==0.6.1) (4.12.2)
8.680 Requirement already satisfied: filelock in /usr/local/python3.10.5/lib/python3.10/site-packages (from torch<=2.3.1,>=2.0.0->lmdeploy==0.6.1) (3.16.1)
8.681 Requirement already satisfied: sympy in /usr/local/python3.10.5/lib/python3.10/site-packages (from torch<=2.3.1,>=2.0.0->lmdeploy==0.6.1) (1.13.3)
8.682 Requirement already satisfied: networkx in /usr/local/python3.10.5/lib/python3.10/site-packages (from torch<=2.3.1,>=2.0.0->lmdeploy==0.6.1) (3.4)
8.682 Requirement already satisfied: jinja2 in /usr/local/python3.10.5/lib/python3.10/site-packages (from torch<=2.3.1,>=2.0.0->lmdeploy==0.6.1) (3.1.4)
8.683 Requirement already satisfied: fsspec in /usr/local/python3.10.5/lib/python3.10/site-packages (from torch<=2.3.1,>=2.0.0->lmdeploy==0.6.1) (2024.9.0)
8.688 Requirement already satisfied: requests in /usr/local/python3.10.5/lib/python3.10/site-packages (from torchvision<=0.18.1,>=0.15.0->lmdeploy==0.6.1) (2.32.3)
8.851 Collecting starlette<0.39.0,>=0.37.2 (from fastapi->lmdeploy==0.6.1)
8.900   Downloading http://mirrors.aliyun.com/pypi/packages/b7/9c/93f7bc03ff03199074e81974cc148908ead60dcf189f68ba1761a0ee35cf/starlette-0.38.6-py3-none-any.whl (71 kB)
9.134 Collecting termcolor (from fire->lmdeploy==0.6.1)
9.185   Downloading http://mirrors.aliyun.com/pypi/packages/7f/be/df630c387a0a054815d60be6a97eb4e8f17385d5d6fe660e1c02750062b4/termcolor-2.5.0-py3-none-any.whl (7.8 kB)
9.274 Collecting addict (from mmengine-lite->lmdeploy==0.6.1)
9.459   Downloading http://mirrors.aliyun.com/pypi/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl (3.8 kB)
9.644 Collecting rich (from mmengine-lite->lmdeploy==0.6.1)
9.700   Downloading http://mirrors.aliyun.com/pypi/packages/67/91/5474b84e505a6ccc295b2d322d90ff6aa0746745717839ee0c5fb4fdcceb/rich-13.9.2-py3-none-any.whl (242 kB)
9.944 Collecting yapf (from mmengine-lite->lmdeploy==0.6.1)
10.00   Downloading http://mirrors.aliyun.com/pypi/packages/66/c9/d4b03b2490107f13ebd68fe9496d41ae41a7de6275ead56d0d4621b11ffd/yapf-0.40.2-py3-none-any.whl (254 kB)
10.10 Collecting anyio<5,>=3.5.0 (from openai->lmdeploy==0.6.1)
10.16   Downloading http://mirrors.aliyun.com/pypi/packages/9e/ef/7a4f225581a0d7886ea28359179cb861d7fbcdefad29663fc1167b86f69f/anyio-4.6.0-py3-none-any.whl (89 kB)
10.18 Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/python3.10.5/lib/python3.10/site-packages (from openai->lmdeploy==0.6.1) (1.9.0)
10.28 Collecting httpx<1,>=0.23.0 (from openai->lmdeploy==0.6.1)
10.48   Downloading http://mirrors.aliyun.com/pypi/packages/56/95/9377bcb415797e44274b51d46e3249eba641711cf3348050f76ee7b15ffc/httpx-0.27.2-py3-none-any.whl (76 kB)
10.66 Collecting jiter<1,>=0.4.0 (from openai->lmdeploy==0.6.1)
10.86   Downloading http://mirrors.aliyun.com/pypi/packages/6b/ab/07e67b0a9ad816f5130def05537177f2efdfe451480a584ae9fbb31cdaf8/jiter-0.6.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (337 kB)
10.96 Collecting sniffio (from openai->lmdeploy==0.6.1)
10.97   Downloading http://mirrors.aliyun.com/pypi/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl (10 kB)
11.06 Collecting interegular (from outlines->lmdeploy==0.6.1)
11.11   Downloading http://mirrors.aliyun.com/pypi/packages/c4/01/72d6472f80651673716d1deda2a5bbb633e563ecf94f4479da5519d69d25/interegular-0.3.3-py37-none-any.whl (23 kB)
11.29 Collecting lark (from outlines->lmdeploy==0.6.1)
11.45   Downloading http://mirrors.aliyun.com/pypi/packages/2d/00/d90b10b962b4277f5e64a78b6609968859ff86889f5b898c1a778c06ec00/lark-1.2.2-py3-none-any.whl (111 kB)
11.52 Collecting nest-asyncio (from outlines->lmdeploy==0.6.1)
11.53   Downloading http://mirrors.aliyun.com/pypi/packages/a0/c4/c2971a3ba4c6103a3d10c4b0f24f461ddc027f0f09763220cf35ca1401b3/nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
11.54 Requirement already satisfied: cloudpickle in /usr/local/python3.10.5/lib/python3.10/site-packages (from outlines->lmdeploy==0.6.1) (3.0.0)
11.64 Collecting diskcache (from outlines->lmdeploy==0.6.1)
11.70   Downloading http://mirrors.aliyun.com/pypi/packages/3f/27/4570e78fc0bf5ea0ca45eb1de3818a23787af9b390c0b0a0033a1b8236f9/diskcache-5.6.3-py3-none-any.whl (45 kB)
11.92 Collecting referencing (from outlines->lmdeploy==0.6.1)
11.94   Downloading http://mirrors.aliyun.com/pypi/packages/b7/59/2056f61236782a2c86b33906c025d4f4a0b17be0161b63b70fd9e8775d36/referencing-0.35.1-py3-none-any.whl (26 kB)
12.03 Collecting jsonschema (from outlines->lmdeploy==0.6.1)
12.05   Downloading http://mirrors.aliyun.com/pypi/packages/69/4a/4f9dbeb84e8850557c02365a0eee0649abe5eb1d84af92a25731c6c0f922/jsonschema-4.23.0-py3-none-any.whl (88 kB)
12.15 Collecting datasets (from outlines->lmdeploy==0.6.1)
12.42   Downloading http://mirrors.aliyun.com/pypi/packages/be/3e/e58d4db4cfe71e3ed07d169af24db30cfd582e16f977378bd43fd7ec1998/datasets-3.0.1-py3-none-any.whl (471 kB)
12.65 Collecting pycountry (from outlines->lmdeploy==0.6.1)
12.73   Downloading http://mirrors.aliyun.com/pypi/packages/b1/ec/1fb891d8a2660716aadb2143235481d15ed1cbfe3ad669194690b0604492/pycountry-24.6.1-py3-none-any.whl (6.3 MB)
13.28      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 11.6 MB/s eta 0:00:00
13.48 Collecting airportsdata (from outlines->lmdeploy==0.6.1)
13.68   Downloading http://mirrors.aliyun.com/pypi/packages/af/57/57635b0af4a23723b2b43109aa4eae7395d346d1eed8a00691cf3acfc5bd/airportsdata-20241001-py3-none-any.whl (912 kB)
13.76      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 912.7/912.7 kB 11.7 MB/s eta 0:00:00
13.83 Collecting outlines-core==0.1.0 (from outlines->lmdeploy==0.6.1)
13.92   Using cached http://mirrors.aliyun.com/pypi/packages/66/1e/4ace9b406b992241e2102ad86f33aec1e6ab8af7aad177f4ea9425900bc6/outlines_core-0.1.0.tar.gz (55 kB)
13.96   Preparing metadata (pyproject.toml): started
13.96   Running command Preparing metadata (pyproject.toml)
14.18   Traceback (most recent call last):
14.18     File "/usr/local/python3.10.5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
14.18       main()
14.19     File "/usr/local/python3.10.5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
14.19       json_out['return_val'] = hook(**hook_input['kwargs'])
14.19     File "/usr/local/python3.10.5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
14.19       return hook(metadata_directory, config_settings)
14.19     File "/usr/local/python3.10.5/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
14.19       self.run_setup()
14.19     File "/usr/local/python3.10.5/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
14.19       exec(code, locals())
14.19     File "<string>", line 4, in <module>
14.19   ModuleNotFoundError: No module named 'setuptools_rust'
14.22   error: subprocess-exited-with-error
14.22   
14.22   × Preparing metadata (pyproject.toml) did not run successfully.
14.22   │ exit code: 1
14.22   ╰─> See above for output.
14.22   
14.22   note: This error originates from a subprocess, and is likely not a problem with pip.
14.22   full command: /usr/local/python3.10.5/bin/python3.10 /usr/local/python3.10.5/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpz3al2rge
14.23   cwd: /tmp/pip-install-f27tzl3v/outlines-core_bbd5c6d0060040289f46fd010b08321a
14.23   Preparing metadata (pyproject.toml): finished with status 'error'
14.24 error: metadata-generation-failed
14.24 
14.24 × Encountered error while generating package metadata.
14.24 ╰─> See above for output.
14.24 
14.24 note: This is an issue with the package mentioned above, not pip.
14.24 hint: See above for details.
```

**Comment by lvhan028** [comment]
This is invoked by `outlines`. LMDeploy latest main branch has restrict its version "outlines<0.1.0". 
Can you try the latest code to build the image on Ascend platform?

**Comment by CyCle1024** [comment]
> This is invoked by `outlines`. LMDeploy latest main branch has restrict its version "outlines<0.1.0". Can you try the latest code to build the image on Ascend platform?

Reference PR already solve this issue: https://github.com/InternLM/lmdeploy/pull/2559

**Comment by wangyuanxiong-hub** [comment]
> > This is invoked by `outlines`. LMDeploy latest main branch has restrict its version "outlines<0.1.0". Can you try the latest code to build the image on Ascend platform?
> 
> Reference PR already solve this issue: #2559

OH！Thanks, this solves my problem

**Comment by lvhan028** [comment]
closing it since the latest main branch already fixed the issue.

**Pull request closed without merging**
