### PR TITLE
[Feature] Add params config for api server web_ui

### PR DESCRIPTION
**Pull request by amulil**
## Motivation
the current api server web demo is simple, I want to change some params on the web.

## Modification
Just add three new params `top_p`、`temperature`、`Maximum new tokens`(`request_output_len` in the code)
截屏2023-11-22 18 34 52

## Checklist
1. Pre-commit or other linting tools are used to fix the potential lint issues. —— **Already run.**
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness. —— **I test the code change by changing the params value and then observe the model output, I think the output is right.**

### CODE REVIEW

**Review by AllentDan — COMMENTED** [review]
Hi, @amulil Sorry for the late reply. Would you mind making the same change to turbomind backend and triton server backend for the WebUI?

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by RunningLeon** [comment]
Hope we can use same ui for gradio as the backend or as pure frontend.

**Comment by amulil** [comment]
> Hi, @amulil Sorry for the late reply. Would you mind making the same change to turbomind backend and triton server backend for the WebUI?

OK, I will do it this weekend.

**Review by AllentDan — APPROVED** [review]
LGTM

**Pull request merged**
