### PR TITLE
Support min_tokens, min_p parameters for api_server

### PR DESCRIPTION
**Pull request by AllentDan**

### CODE REVIEW

**Comment by AllentDan** [comment]
The weird thing is, min_new_tokens did not work. @irexyc

**Comment by irexyc** [comment]
```
from lmdeploy import pipeline
pipe = pipeline('/nvme/shared/vicuna-7b-v1.5/')
pipe('hello', gen_config=GenerationConfig())
# Response(text='ಠ\\_ಠ', generate_token_len=7, input_token_len=41, session_id=8, finish_reason='stop', token_ids=[227, 181, 163, 20122, 227, 181, 163], logprobs=None, index=0)

pipe('hello', gen_config=GenerationConfig(min_new_tokens=8))
# Response(text='ಠ\\_ಠ How can I assist you today?', generate_token_len=14, input_token_len=41, session_id=7, finish_reason='stop', token_ids=[227, 181, 163, 20122, 227, 181, 163, 1128, 508, 306, 6985, 366, 9826, 29973], logprobs=None, index=0)
```

**Comment by AllentDan** [comment]
But if I set `min_new_tokens=100` for internlm2-chat-1_8b, the result is less than 100 tokens.

**Comment by irexyc** [comment]
It only ignore [eos token](https://github.com/InternLM/lmdeploy/blob/main/src/turbomind/layers/sampling_layers/LogitsProcessorLayer.cc#L166-L174) when length of the generated token is less than min_new_tokens. Its behavior should be consistent with [transformers](https://github.com/huggingface/transformers/blob/162056a3f433132fa6ce32c87663742803036b59/src/transformers/generation/logits_process.py#L170), except that transformers support multiple eos tokens

But If encountered stop words token, it will still stop.

**Review by irexyc — APPROVED** [review]

**Comment by lvhan028** [comment]
Should we update `completions_v1` as well?

**Comment by AllentDan** [comment]
It is a lagecy api from OpenAI. I tend to not update it.

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
