### PR TITLE
docs: fix Ada compatibility

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

as titled cc @lvhan028 @AllentDan 

## Modification

as titled

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
May also update the corresponding Chinese doc

**Comment by zhyncs** [comment]
> May also update the corresponding Chinese doc

Chinese is correct.

**Review by lvhan028 — APPROVED** [review]

**Comment by isidentical** [comment]
Is H100s supported?

**Comment by zhyncs** [comment]
Support but not specifically optimized.

**Pull request merged**
