### PR TITLE
Support CORS for openai api server

### PR DESCRIPTION
**Pull request by aisensiy**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Support CORS for openai api.

## Modification

Add CORS headers.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
@aisensiy could you please explain more about the motivation?
I

**Comment by lvhan028** [comment]
Shouldn't the server who is listening to 3000 port deal with it?

**Comment by AllentDan** [comment]
Can we make it an option just like [FastChat](https://github.com/vllm-project/vllm/blob/20f7cc4cdebcbcad788fbe1b06e5e07f8d145b77/vllm/entrypoints/openai/api_server.py#L601)?
Maybe we can provide more args to launch api_server.

**Comment by tpoisonooo** [comment]
Yes CORS does matters for web developer, please make it as an option.  @aisensiy

**Comment by tpoisonooo** [comment]
@aisensiy  Excellent, please make it as an option, **enable CORS** by default.

**Review by tpoisonooo — APPROVED** [review]
make it optional, enable CORS by default.

**Review by AllentDan — APPROVED** [review]
LGTM

**Pull request merged**
