### PR TITLE
Open the streaming output at the commencement of benchmarking the first token's latency.

### PR DESCRIPTION
**Pull request by lvhan028**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

The metric "first token latency" is wrong when benchmarking token generation

## Modification

Change to streaming output

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by grimoire** [comment]
streaming will slow down profiling

**Comment by lvhan028** [comment]
why?

> streaming will slow down profiling

What's the root cause?

**Comment by grimoire** [comment]
Can we visualize the timeline with nsys？

**Comment by lvhan028** [comment]
> Can we visualize the timeline with nsys？

OK. I'll do it

**Comment by lzhangzz** [comment]
It seems to me that the execution of inference is blocked by stream callback due to GIL. The callback will likely return only when the main thread reaches `Queue.get()`, which will release GIL because the blocking nature of `get()`.

**Pull request closed without merging**
