### PR TITLE
add mistral-7b-instruct-v0.1 template

### PR DESCRIPTION
**Pull request by maxchiron**
## add mistral-7b-instruct-v0.1 template

**I just copy the llama2 template and replace the signals to `<s></s>` from `<<SYS>><</SYS>>` .
So please check if I was wrong before merge. If reject, please let me know positions I need to modify. Thanks.**

### CODE REVIEW

**Comment by lvhan028** [comment]
Hi, @maxchiron 
I think mistral chat template is not enough,  @irexyc used to support it in #524.
But after the investigation, we found the core of mistral is window attention. And we haven't implemented it yet.

**Comment by maxchiron** [comment]
> Hi, @maxchiron I think mistral chat template is not enough, @irexyc used to support it in #524. But after the investigation, we found the core of mistral is window attention. And we haven't implemented it yet.

---

Thanks for repying, Mr. owl. @lvhan028 

## The reason I init this PR is that I found the following steps worked:

```bash
lmdeploy convert internlm-chat-7b Mistral-7B-Instruct-v0.1/
lmdeploy serve gradio ./workspace
```
You can see, lmdeploy use internlm config to convert mistral successfully, than the converted mistral deploied successfully too.

---
## Q
1. Basing on your reply that `window attention has not been implemented yet`, could I take its successful running as a cripple performance?
2. xtuner just add a template to support the finetuning and deploy of  `zephyer (which finetuned on mistral)` . Is this of any reference value for the implementation of lmdeploy in this matter?

**Comment by lvhan028** [comment]
Hi, @maxchiron we'll review it soon

**Comment by lvhan028** [comment]
@maxchiron we discussed it internally. We think it is not appropriate to announce lmdeploy supporting mistral if the window attention is not implemented.

**Comment by maxchiron** [comment]
> @maxchiron we discussed it internally. We think it is not appropriate to announce lmdeploy supporting mistral if the window attention is not implemented.

Okay, thanks for reviewing~ ❤️

**Pull request closed without merging**
