### PR TITLE
support deploy qwen-14b-chat

### PR DESCRIPTION
**Pull request by irexyc**
## Motivation

support deploy qwen-14b-chat
https://huggingface.co/Qwen/Qwen-14B-Chat

### CODE REVIEW

**Comment by Xu-Chen** [comment]
🐮

**Review by lvhan028 — APPROVED** [review]

**Review by AllentDan — APPROVED** [review]
LGTM

**Comment by leethu2012** [comment]
请问是用以下命令进行转换吗：
python3 -m lmdeploy.serve.turbomind.deploy qwen-14b /path/to/Qwen-14B-Chat
我运行这个命令时报错：
tokenizer model /home/ma-user/work/models/Qwen-14B-Chat/tokenizer.model does not exist

**Comment by AllentDan** [comment]
需要指定 --model_format qwen

**Pull request merged**
