### PR TITLE
[maca] add maca backend support.

### PR DESCRIPTION
**Pull request by Reinerzhou**
## Motivation

add maca backend support.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by jinminxi104 — APPROVED** [review]

**Review by grimoire — APPROVED** [review]
LGTM

**Comment by QwertyJack** [comment]
Could you please kindly explain what ***maca*** is?

**Comment by lvhan028** [comment]
沐曦

> Could you please kindly explain what _**maca**_ is?

**Comment by Reinerzhou** [comment]
> Could you please kindly explain what _**maca**_ is?

A backend to support inference on muxi platform， just like ascend and cuda  that has supported in lmdeploy。

**Pull request merged**
