### PR TITLE
Fix llama_triton_example

### PR DESCRIPTION
**Pull request by AllentDan**
https://github.com/InternLM/lmdeploy/blob/fdb95313f7b99c44309f504b3f68b622f5fd6523/src/turbomind/models/llama/LlamaBatch.cc#L1015-L1022

### CODE REVIEW

**Comment by zhyncs** [comment]
@AllentDan May you give a request example

**Comment by AllentDan** [comment]
Just the example failed. May run `build/bin/llama_triton_example examples/cpp/llama/llama_config.ini examples/cpp/llama/start_ids.csv`, it will raise error.

**Comment by zhyncs** [comment]
> Just the example failed. May run `build/bin/llama_triton_example examples/cpp/llama/llama_config.ini examples/cpp/llama/start_ids.csv`, it will raise an error.

make sense https://github.com/InternLM/lmdeploy/pull/1246

**Comment by zhyncs** [comment]
LGTM

**Review by lzhangzz — APPROVED** [review]

**Pull request merged**
