### PR TITLE
variable `CTA_H` & fix qkv bias

### PR DESCRIPTION
**Pull request by lzhangzz**
- Support 1-16 query group size
- Better partitioning of query heads
- Fix qkv bias in case of GQA
- Avoid integer overflow for long sequence & large batch size
- Isolate the compilation of reduce kernels

### CODE REVIEW

**Review by lvhan028 — APPROVED** [review]

**Comment by lvhan028** [comment]
dataset                                 version    metric         mode    qwen2-chat-32b
--------------------------------------  ---------  -------------  ------  ----------------
ceval                                       -          naive_average  gen     81.35
mmlu                                      -          naive_average  gen     74.88
gsm8k                                   1d7fe4     accuracy        gen     77.79

**Comment by lvhan028** [comment]
| dataset | version | metric        | mode | llama2-7b-chat | internlm-chat-7b | internlm-chat-20b | internlm2-chat-7b | internlm2-chat-20b | qwen-chat-7b | qwen2-chat-7b |
|---------|---------|---------------|------|----------------|------------------|-------------------|-------------------|--------------------|--------------|---------------|
| ceval   | -       | naive_average | gen  | 28.30          | 52.90            | 54.64             | 60.45             | 62.86              | 59.46        | 70.81         |
| mmlu    | -       | naive_average | gen  | 35.93          | 48.58            | 59.45             | 63.90             | 66.58              | 57.40        | 61.48         |
| gsm8k   | 1d7fe4  | accuracy      | gen  | 28.28          | 33.51            | 47.54             | 70.43             | 79.53              | 54.21        | 55.50         |

**Comment by lvhan028** [comment]
@irexyc may check if it works on VLM models, especially internvl which has q_group_size 7

**Comment by lvhan028** [comment]
llama2-70b(tp4): 8.54
llama3-8b: 24.89
llama2-13b: 8.57
llama2-7b: 15.0
internlm2-7b: 24.2
internlm2-20b: 10.68

**Review by irexyc — APPROVED** [review]

**Pull request merged**
