### PR TITLE
bump version to v0.2.4

### PR DESCRIPTION
**Pull request by lvhan028**

### CODE REVIEW

**Comment by zhyncs** [comment]
Hi @lvhan028 `deployment to prod` has not been executed.

**Comment by lvhan028** [comment]
image

**Comment by lvhan028** [comment]
ODD
image

**Comment by zhyncs** [comment]
Hi @lvhan028 https://github.com/InternLM/lmdeploy/releases/tag/v0.2.4 missing whl

**Comment by lvhan028** [comment]
OMG

**Comment by lvhan028** [comment]
done @zhyncs

**Pull request merged**
