### PR TITLE
Fix llama3.1 chat template

### PR DESCRIPTION
**Pull request by fzyzcjy**
It seems https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/blob/main/tokenizer_config.json says:

image

i.e. July 26 instead July 23.

---

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by AllentDan — APPROVED** [review]

**Comment by AllentDan** [comment]
Not a big deal. https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_1 gives `23 July 2024`

**Comment by fzyzcjy** [comment]
Interesting! Then llama itself is inconsistent about this...

**Comment by lvhan028** [comment]
Hi, @fzyzcjy 
Thanks for your contribution
This PR didn't pass the unit test.
Can you fix it?
https://github.com/InternLM/lmdeploy/actions/runs/12192401746/job/34297273083?pr=2862

**Comment by fzyzcjy** [comment]
Sure, done!

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
