### PR TITLE
fix: gradio gr.Button.update deprecated after 4.0.0

### PR DESCRIPTION
**Pull request by hscspring**
## Motivation

gradio >= 4.0.0 doesn't support `gr.Button.update`

## Modification

make gradio version < 4.0.0

### CODE REVIEW

**Review by RunningLeon — COMMENTED** [review]
may update accordingly after pr https://github.com/InternLM/lmdeploy/pull/580 is merged

**Comment by lvhan028** [comment]
@RunningLeon Let's leave #580  to ourselves

**Comment by hscspring** [comment]
nice, update the related code might be better

**Review by AllentDan — APPROVED** [review]
LGTM

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
