### PR TITLE
fix decoding kernel for deepseekv2

### PR DESCRIPTION
**Pull request by grimoire**
Fix decoding kernel for GQA with large `kv_group`.

### CODE REVIEW

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by lvhan028** [comment]
@RunningLeon could you help start a oc evaluation?

**Comment by RunningLeon** [comment]
> @RunningLeon could you help start a oc evaluation with gsm8k and math datasets?

on which models? deepseekv2-chat is too large and needs 8 nv cards...

**Comment by RunningLeon** [comment]
> @RunningLeon could you help start a oc evaluation with gsm8k and math datasets?

Looks normal.
>
| dataset | version | metric | mode | DeepSeek-V2-Chat-pytorch |
|----- | ----- | ----- | ----- | -----|
| gsm8k | a58960 | accuracy | gen | 91.36 |

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
