### PR TITLE
compat internlm2 for pytorch engine

### PR DESCRIPTION
**Pull request by RunningLeon**
## Motivation

compat internlm2 for pytorch engine

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]

**Comment by grimoire** [comment]
https://github.com/InternLM/lmdeploy/blob/da439dfd186265faf8074797f5ed4c8a3f3c4f2d/lmdeploy/lite/quantization/calibration.py#L172
```python
                    use_new_cache = type(mod).__name__ in ('LlamaDecoderLayer',
                                                           'Qwen2DecoderLayer')
                    if type(mod).__name__ == 'InternLM2DecoderLayer':
                        use_new_cache = hasattr(mod.attention, 'layer_idx')
```

**Comment by zhulinJulia24** [comment]
4bits quantization is still fail

the command is: 
`lmdeploy lite auto_awq /nvme/qa_test_models/OpenGVLab/InternVL-Chat-V1-5 --work-dir /nvme/qa_test_models/OpenGVLab/InternVL-Chat-V1-5-inner-4bits --batch-size 32`


the error log is: 
```
E       AssertionError: You are using a model of type internlmxcomposer2 to instantiate a model of type internlm2. This is not supported for all configurations of models and can yield errors.
319E         /usr/local/lib/python3.8/dist-packages/datasets/load.py:1461: FutureWarning: The repository for ptb_text_only contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at ​https://hf.co/datasets/ptb_text_only
320E         You can avoid this message in future by passing the argument `trust_remote_code=True`.
321E         Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
322E           warnings.warn(
323E         /usr/local/lib/python3.8/dist-packages/datasets/load.py:1461: FutureWarning: The repository for ptb_text_only contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at ​https://hf.co/datasets/ptb_text_only
324E         You can avoid this message in future by passing the argument `trust_remote_code=True`.
325E         Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
326E           warnings.warn(
327E         Traceback (most recent call last):
328E           File "/usr/local/bin/lmdeploy", line 8, in <module>
329E             sys.exit(run())
330E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/cli/entrypoint.py", line 37, in run
331E             args.run(args)
332E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/cli/lite.py", line 137, in auto_awq
333E             auto_awq(**kwargs)
334E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/auto_awq.py", line 96, in auto_awq
335E             vl_model, model, tokenizer, work_dir = calibrate(model,
336E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 235, in calibrate
337E             calib_ctx.calibrate(all_data)
338E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 323, in calibrate
339E             _ = model(data.to(self.device))
340E           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
341E             return self._call_impl(*args, **kwargs)
342E           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
343E             return forward_call(*args, **kwargs)
344E           File "/github/home/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-4khd-7b/modeling_internlm2.py", line 958, in forward
345E             layer_outputs = decoder_layer(
346E           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
347E             return self._call_impl(*args, **kwargs)
348E           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
349E             return forward_call(*args, **kwargs)
350E           File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 186, in _forward
351E             ori_idx = self_attn.layer_idx
352E           File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1688, in __getattr__
353E             raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
354E         AttributeError: 'InternLM2Attention' object has no attribute 'layer_idx'
355E         
356E       assert False
```

**Comment by RunningLeon** [comment]
@zhulinJulia24 hi, pls try with  the latest code again.

**Review by lvhan028 — APPROVED** [review]

**Comment by zhulinJulia24** [comment]
> @zhulinJulia24 hi, pls try with the latest code again.

fixed!

**Pull request merged**
