### PR TITLE
docs: update cache-max-entry-count help message

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

as titled cc @lvhan028 @AllentDan 

## Modification

as titled

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by AllentDan — APPROVED** [review]

**Review by lvhan028 — APPROVED** [review]

**Comment by zhyncs** [comment]
Sorry for introducing the lint failure with flake8

**Comment by zhyncs** [comment]
```diff
@ lmdeploy/cli/utils.py:382 @ class ArgumentHelper:
            '--cache-max-entry-count',
            type=float,
            default=0.8,
-           help=
-           'The percentage of free gpu memory occupied by the k/v cache, excluding weights'
+           help=\
+          'The percentage of free gpu memory occupied by the k/v cache, excluding weights' # noqa
        )
```

Hi @AllentDan May you help update this? Thanks.

**Comment by lvhan028** [comment]
I am going to fix it in #1852

**Comment by zhyncs** [comment]
> I am going to fix it in #1852

Thanks!

**Pull request merged**
