### PR TITLE
Fix compatibility issues with Pydantic 2

### PR DESCRIPTION
**Pull request by aisensiy**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Running command 

```bash
python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 8080  --instance_num 32 --tp 1
```

and start to call the `/chat/completions` api will show error messages like this:

```
/output/.pylibs/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py:170: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.3/migration/
  data = chunk.json(exclude_unset=True, ensure_ascii=False)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/output/.pylibs/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/output/.pylibs/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/output/.pylibs/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/output/.pylibs/lib/python3.8/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/output/.pylibs/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 170, in completion_stream_generator
    data = chunk.json(exclude_unset=True, ensure_ascii=False)
  File "/output/.pylibs/lib/python3.8/site-packages/typing_extensions.py", line 2360, in wrapper
    return arg(*args, **kwargs)
  File "/output/.pylibs/lib/python3.8/site-packages/pydantic/main.py", line 960, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```

## Modification

Follow the instructions of the warning messages and [migrate codes for Pydantic 2](https://docs.pydantic.dev/2.3/migration/).

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by AllentDan** [comment]
@aisensiy Hi, could you provide the fastapi and pedantic version? I used `pydantic==2.3.0` and `fastapi==0.103.1` and lmdeploy works fine.

**Comment by AllentDan** [comment]
> The same, `pydantic==2.3.0` and `fastapi==0.103.1`. Maybe it is because of the python version? I have this issue using `python 3.8`.

I tried python 3.8 inside the docker. Could not reproduce the error.

**Comment by AllentDan** [comment]
Hi, I reproduced the error finally with the streaming case. Thanks for the wonderful pull request.

**Review by AllentDan — APPROVED** [review]
LGTM

**Review by irexyc — APPROVED** [review]

**Pull request merged**
