### PR TITLE
Support mixtral for pytorch engine

### PR DESCRIPTION
**Pull request by RunningLeon**
## Motivation

Support [mistralai/Mixtral-8x7B-Instruct-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1) for pytorch engine

`lmdeploy chat torch mistralai/Mixtral-8x7B-Instruct-v0.1 --tp 4`

> [!WARNING]
> may have to fix conflicts after pr https://github.com/InternLM/lmdeploy/pull/1075
## Modification

- add patched modules to support mixtral
- add chat template for mixtral

## BC-breaking (Optional)

None

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
May resolve the conflicts

**Review by grimoire — APPROVED** [review]

**Comment by lvhan028** [comment]
At lest 4 A100 GPU?

**Comment by lvhan028** [comment]
```shell
CUDA_VISIBLE_DEVICES=6,7 lmdeploy chat torch /workspace/models-140/mistralai/Mixtral-8x7B-Instruct-v0.1 --tp 2 --cache-max-entry-count 0.5
```
raise error
```
2024-02-26 06:20:03,738 - lmdeploy - ERROR - rank[1] failed with error: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 1 has a total capacty of 79.21 GiB of which 58.62 MiB is free. Process 167559 has 43.96 GiB memory in use. Process 167560 has 35.19 GiB memory in use. Of the allocated memory 33.95 GiB is allocated by PyTorch, and 104.99 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
It seems that the weight size of Mixtral-8x7B-Instruct-v0.1 is about 90+G. Two GPUs should be enough

**Comment by RunningLeon** [comment]
> ```shell
> CUDA_VISIBLE_DEVICES=6,7 lmdeploy chat torch /workspace/models-140/mistralai/Mixtral-8x7B-Instruct-v0.1 --tp 2 --cache-max-entry-count 0.5
> ```
> 
> raise error
> 
> ```
> 2024-02-26 06:20:03,738 - lmdeploy - ERROR - rank[1] failed with error: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 1 has a total capacty of 79.21 GiB of which 58.62 MiB is free. Process 167559 has 43.96 GiB memory in use. Process 167560 has 35.19 GiB memory in use. Of the allocated memory 33.95 GiB is allocated by PyTorch, and 104.99 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```
> 
> It seems that the weight size of Mixtral-8x7B-Instruct-v0.1 is about 90+G. Two GPUs should be enough

@lvhan028 
Should work with tp=2 after fixing

**Comment by lvhan028** [comment]
I tried `tp=2` and 4 processes were launched. Is it expected?
After the CLI is launched, I did nothing. But I found the GPU-Util of GPU 1 is 100% while the other is 0%, is this expected?

```
Every 1.0s: nvidia-smi -i 0,1                                                                                       Tue Feb 27 11:13:35 2024

Tue Feb 27 11:13:35 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:0B:00.0 Off |                    0 |
| N/A   27C    P0    78W / 400W |  74692MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:10:00.0 Off |                    0 |
| N/A   28C    P0    85W / 400W |  74585MiB / 81920MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     85306      C   ...da/envs/triton/bin/python      504MiB |
|    0   N/A  N/A     85479      C   ...da/envs/triton/bin/python    74178MiB |
|    1   N/A  N/A     85479      C   ...da/envs/triton/bin/python      411MiB |
|    1   N/A  N/A     85480      C   ...da/envs/triton/bin/python    74154MiB |
+-----------------------------------------------------------------------------+
```

**Comment by RunningLeon** [comment]
@

> I tried `tp=2` and 4 processes were launched. Is it expected? After the CLI is launched, I did nothing. But I found the GPU-Util of GPU 1 is 100% while the other is 0%, is this expected?
> 
> ```
> Every 1.0s: nvidia-smi -i 0,1                                                                                       Tue Feb 27 11:13:35 2024
> 
> Tue Feb 27 11:13:35 2024
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA A100-SXM...  Off  | 00000000:0B:00.0 Off |                    0 |
> | N/A   27C    P0    78W / 400W |  74692MiB / 81920MiB |      0%      Default |
> |                               |                      |             Disabled |
> +-------------------------------+----------------------+----------------------+
> |   1  NVIDIA A100-SXM...  Off  | 00000000:10:00.0 Off |                    0 |
> | N/A   28C    P0    85W / 400W |  74585MiB / 81920MiB |    100%      Default |
> |                               |                      |             Disabled |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A     85306      C   ...da/envs/triton/bin/python      504MiB |
> |    0   N/A  N/A     85479      C   ...da/envs/triton/bin/python    74178MiB |
> |    1   N/A  N/A     85479      C   ...da/envs/triton/bin/python      411MiB |
> |    1   N/A  N/A     85480      C   ...da/envs/triton/bin/python    74154MiB |
> +-----------------------------------------------------------------------------+
> ```

yes, it's normal.

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
