### PR TITLE
[Refactor & Doc] Improve w8a8 and add docstring

### PR DESCRIPTION
**Pull request by HIT-cwh**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by grimoire** [comment]
Please add more docstring to solve lint
```
| pytorch_poc/modeling/modeling_baichuan.py               |    33 |   11 |    22 |    67% |
| pytorch_poc/modeling/modeling_internlm.py               |    40 |   14 |    26 |    65% |
| pytorch_poc/modeling/modeling_llama.py                  |    44 |   15 |    29 |    66% |
```

**Comment by HIT-cwh** [comment]
> Please add more docstring to solve lint
> 
> ```
> | pytorch_poc/modeling/modeling_baichuan.py               |    33 |   11 |    22 |    67% |
> | pytorch_poc/modeling/modeling_internlm.py               |    40 |   14 |    26 |    65% |
> | pytorch_poc/modeling/modeling_llama.py                  |    44 |   15 |    29 |    66% |
> ```

The code we have here has been borrowed from the HuggingFace Hub, with merely the addition of logic to replace QModule. Ideally, there shouldn't be any necessity to add docstrings for these functions or interfaces. Perhaps, it might be worthwhile to consider excluding these sections of code when evaluating our docstring coverage?

**Comment by grimoire** [comment]
Edit https://github.com/InternLM/lmdeploy/blob/main/.github/workflows/lint.yml to ignore these files.

**Comment by HIT-cwh** [comment]
> Edit https://github.com/InternLM/lmdeploy/blob/main/.github/workflows/lint.yml to ignore these files.

Done!

**Pull request merged**
