### PR TITLE
fix benchmark serving computation mistake

### PR DESCRIPTION
**Pull request by AllentDan**
#629

### CODE REVIEW

**Review by RunningLeon — CHANGES_REQUESTED** [review]
may resolve conflicts with main branch.

**Review by RunningLeon — COMMENTED** [review]
could we support saving results to local csv file for these bechmark scripts?

**Comment by AllentDan** [comment]
We added the support to `profile_generation.py` since there were many combinations in that script.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Review by lvhan028 — APPROVED** [review]

**Comment by lvhan028** [comment]
Output `first token latency` only when `stream_output` is enabled.
The output results is expected to be like this:
```text
first-token latency(min, max, ave):
number of prompt tokens:
number of completion tokens: 
token throughput (completion token): 
token throughput (prompt + completion token): 
PPS (request per second): 
RPM (request per minute): 
```

**Comment by lvhan028** [comment]
再加上一点：在校验生成的token数量，是不是和要求的数量一致。

**Comment by AllentDan** [comment]
> Output `first token latency` only when `stream_output` is enabled. The output results is expected to be like this:
> 
> ```
> first-token latency(min, max, ave):
> number of prompt tokens:
> number of completion tokens: 
> token throughput (completion token): 
> token throughput (prompt + completion token): 
> PPS (request per second): 
> RPM (request per minute): 
> ```

`stream_output` is not an option now in these scripts. Shall we make it an option? Besides, api_server and tritonserver actually always do streaming generation inside.

**Comment by lvhan028** [comment]
> > Output `first token latency` only when `stream_output` is enabled. The output results is expected to be like this:
> > ```
> > first-token latency(min, max, ave):
> > number of prompt tokens:
> > number of completion tokens: 
> > token throughput (completion token): 
> > token throughput (prompt + completion token): 
> > PPS (request per second): 
> > RPM (request per minute): 
> > ```
> 
> `stream_output` is not an option now in these scripts. Shall we make it an option? Besides, api_server and tritonserver actually always do streaming generation inside.

In the RESTful API protocol, `ChatCompletionRequest`, `CompletionRequest` and `GenerateRequest` support both stream and non-stream mode.
I think it is necessary to make `stream_output` an option in profiling scripts

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
