### PR TITLE
chore workflows support python 3.12

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

workflows support python 3.12

## Modification

GitHub actions and scripts

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by irexyc** [comment]
Hava you tried the build whl package?

Currently, we relay torch<=2.1.2,>=2.0.0, but according to https://download.pytorch.org/whl/torch/, the version between the range doesn't support python 3.12

**Comment by zhyncs** [comment]
> Hava you tried the build whl package?
> 
> Currently, we relay [torch<=2.1.2,>=2.0.0](https://github.com/InternLM/lmdeploy/blob/main/requirements/runtime.txt#L13), but according to https://download.pytorch.org/whl/torch/, the version between the range doesn't support python 3.12

Sorry for late response. I will update the progress here after the GitHub action is confirmed.

**Comment by zhyncs** [comment]
> Hava you tried the build whl package?
> 
> Currently, we relay [torch<=2.1.2,>=2.0.0](https://github.com/InternLM/lmdeploy/blob/main/requirements/runtime.txt#L13), but according to https://download.pytorch.org/whl/torch/, the version between the range doesn't support python 3.12

We may update torch version range
https://github.com/InternLM/lmdeploy/blob/24ea5dc57e85156a32620a9d6a9ff884f2917fb4/requirements/runtime.txt#L13
with
```
torch<=2.2.0,>=2.0.0 
```

I've tested https://download.pytorch.org/whl/cu118/torch-2.2.0%2Bcu118-cp312-cp312-linux_x86_64.whl and it works well.

```
sys.platform: linux
Python: 3.12.1 | packaged by Anaconda, Inc. | (main, Jan 19 2024, 15:51:05) [GCC 11.2.0]
CUDA available: True
GPU: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 10.2.1 20210130 (Red Hat 10.2.1-11)
PyTorch: 2.2.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

LMDeploy: 0.2.3+24beeb6
transformers: 4.37.2
fastapi: 0.109.2
pydantic: 2.6.0
```

```
(py312) [username@hostname lmdeploy]# ls lmdeploy/lib | grep python | grep so
_turbomind.cpython-312-x86_64-linux-gnu.so
```

**Comment by irexyc** [comment]
Turbomind backend doesn't require torch engine. It's pytorch backend (with triton) that require specify version.

Based on our previous testing, the pytorch engine seems having issues with the pytorch 2.2

**Comment by zhyncs** [comment]
> Turbomind backend doesn't require torch engine. It's pytorch backend (with triton) that require specify version.
> 
> Based on our previous testing, the pytorch engine seems having issues with the pytorch 2.2

Yes, I've only tested TurboMind and haven't tested the PyTorch engine. Given the concerns you've raised, I think we may put a hold on this pull request for now. Let's wait until the issues you mentioned are resolved before considering moving forward.

**Comment by zhyncs** [comment]
When the time is right, bring it up again. Closing for now.

**Pull request closed without merging**
