### PR TITLE
Optimize TP performance of pytorch engine

### PR DESCRIPTION
**Pull request by grimoire**
TP of pytorch engine is desperately slow because send large tensor through mp.Queue is very slow.
This PR set the main process as RANK0, avoid data exchange between process.

### CODE REVIEW

**Comment by lvhan028** [comment]
test qwen-7b-chat failed
```
 ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
```

**Comment by grimoire** [comment]
Pipeline tested model:

- llama2 7b/13b
- internlm2 7b/20b
- internlm 7b/20b
- qwen1.5 7b
- baichuan2 7b/13b
- chatglm2 6b
- chatglm3 6b
- falcon 7b
- yi 34b
- mistral 7b
- deepseek 1.3b
- mixtral 8x7b
- gemma 7b

**Comment by lvhan028** [comment]
internlm2-20b, tp 2:
previous: 3.54
this pr: 6.39

llama2-70b, tp 4:
previous: 2.0
this pr: 2.3

**Review by lvhan028 — APPROVED** [review]

**Comment by lvhan028** [comment]
model evaluation test pass: llama2-7b, internlm2-7b, qwen-7b, qwen1.5-7b

**Comment by lvhan028** [comment]
在 gms8k 上精度测试不太对
sm8k                                   1d7fe4     accuracy       gen     14.03(llama2)             56.25(internlm-7b)                34.95(qwen-7b)           5.31(qwen1.5-7b)

**Pull request merged**
