### PR TITLE
support Internvl chat llava

### PR DESCRIPTION
**Pull request by irexyc**
## Motivation

support
- https://huggingface.co/OpenGVLab/InternVL-Chat-ViT-6B-Vicuna-7B
- https://huggingface.co/OpenGVLab/InternVL-Chat-ViT-6B-Vicuna-13B
- https://huggingface.co/OpenGVLab/InternVL-Chat-ViT-6B-Vicuna-13B-448px

## Modification

The internvl-chat-llava developed upon older version of llava, so I write a new vision model. And there may be some bugs in their code https://github.com/OpenGVLab/InternVL/issues/86

### CODE REVIEW

**Review by AllentDan — COMMENTED** [review]
May update doc

**Comment by lvhan028** [comment]
Since a new vision model of latest llava is implemented, do we have to install internvl?

**Comment by irexyc** [comment]
We have to install internvl-managed llava

https://github.com/InternLM/lmdeploy/pull/1426/files#diff-0a552478791ffc02ff1cf21fe07cbf33b06a310e174eb90b6a64106e22bfde6bR18-R27

**Comment by lvhan028** [comment]
verify the following cases with model InternVL-Chat-ViT-6B-Vicuna-7B

- [x] pipeline (tp=1, 2)
- [x] gradio
- [x] api_server

**Review by lvhan028 — APPROVED** [review]

**Review by AllentDan — APPROVED** [review]
Tested pipeline and api_server of `InternVL-Chat-ViT-6B-Vicuna-7B`

**Pull request merged**
