### PR TITLE
repetition penalty for long context

### PR DESCRIPTION
**Pull request by irexyc**
## Motivation

address https://github.com/InternLM/lmdeploy/issues/1009 https://github.com/InternLM/lmdeploy/issues/898

去掉Shared Memory 支持更长的 session

### CODE REVIEW

**Comment by irexyc** [comment]
image

**Review by lzhangzz — APPROVED** [review]

**Comment by irexyc** [comment]
before & after （llama-7b）
```
concurrency: 64
elapsed_time: 179.799s

first token latency(s)(min, max, ave): 0.031, 1.292, 0.106
per-token latency(s) percentile(50, 75, 95, 99): [0.024, 0.035, 0.053, 0.074]

number of prompt tokens: 490772
number of completion tokens: 472162
token throughput (completion token): 2626.051 token/s
token throughput (prompt + completion token): 5355.606 token/s
RPS (request per second): 11.124 req/s
RPM (request per minute): 667.411 req/min
--------------------------------------------------


concurrency: 64
elapsed_time: 179.440s

first token latency(s)(min, max, ave): 0.037, 1.361, 0.104
per-token latency(s) percentile(50, 75, 95, 99): [0.024, 0.033, 0.05, 0.073]

number of prompt tokens: 490772
number of completion tokens: 472162
token throughput (completion token): 2631.309 token/s
token throughput (prompt + completion token): 5366.330 token/s
RPS (request per second): 11.146 req/s
RPM (request per minute): 668.747 req/min
--------------------------------------------------


```

**Comment by lzhangzz** [comment]
> before & after （llama-7b）

It seems that llama-7b does not use repetition penalty by default.

**Comment by irexyc** [comment]
> It seems that llama-7b does not use repetition penalty by default.

I added `repetition_penalty=1.005` in stream_infer manually.
https://github.com/InternLM/lmdeploy/blob/main/benchmark/profile_throughput.py#L88-L97

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
