### PR TITLE
bump version to v0.2.3

### PR DESCRIPTION
**Pull request by lvhan028**

### CODE REVIEW

**Comment by zhyncs** [comment]
Hi @lvhan028 hold on please

After https://github.com/InternLM/lmdeploy/pull/1085, this doesn't work as before.
```bash
python3 -m lmdeploy serve api_server /workdir/workspace
```
traceback
```
  File "/workdir/lmdeploy/lmdeploy/serve/async_engine.py", line 111, in _build_turbomind
    raise ArgumentError('Please set model_name or backend_config.')
TypeError: __init__() missing 1 required positional argument: 'message'
```
I have to set model-name explicitly like this.
```bash
python3 -m lmdeploy serve api_server /workdir/workspace --model-name llama2
```
Is this an expected feature or a bug? If it’s a bug, may I fix it before releasing it?

**Comment by lvhan028** [comment]
@irexyc

**Comment by irexyc** [comment]
@zhyncs 

I can't reproduce your error, are you using the latest main code? 

According to your error, the error line is 111, but the code in main branch is at line 109
```
  File "/workdir/lmdeploy/lmdeploy/serve/async_engine.py", line 111, in _build_turbomind
    raise ArgumentError('Please set model_name or backend_config.')
TypeError: __init__() missing 1 required positional argument: 'message'
```

**Comment by zhyncs** [comment]
> @zhyncs
> 
> I can't reproduce your error, are you using the latest main code?
> 
> According to your error, the error line is 111, but the code in main branch is at line [109](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/async_engine.py#L109)
> 
> ```
>   File "/workdir/lmdeploy/lmdeploy/serve/async_engine.py", line 111, in _build_turbomind
>     raise ArgumentError('Please set model_name or backend_config.')
> TypeError: __init__() missing 1 required positional argument: 'message'
> ```

Yes, I use the latest main code.

**Comment by zhyncs** [comment]
@irexyc use the llama 2 13b chat workspace please

**Comment by irexyc** [comment]
Found the reason

**Comment by zhyncs** [comment]
Since the `_from_workspace` handles the `model_name`
https://github.com/InternLM/lmdeploy/blob/41dd74044554619314283c3a5b9f32a28f2dafd3/lmdeploy/turbomind/turbomind.py#L374
We don't need raise the exception like this
https://github.com/InternLM/lmdeploy/blob/41dd74044554619314283c3a5b9f32a28f2dafd3/lmdeploy/serve/async_engine.py#L107-L109

**Comment by zhyncs** [comment]
> Found the reason

Fine, may I send the pr? It's up to you.

**Comment by zhyncs** [comment]
Hi @irexyc May you help review this pr https://github.com/InternLM/lmdeploy/pull/1125? Thanks.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Pull request merged**
