### PR TITLE
feat: skip invokeFlattenKV_v2_ when fp16 and bf16 with CacheType::kBlock

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation and Modification

as titled

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lzhangzz** [comment]
How about BF16, it should be the same as FP16.

**Comment by zhyncs** [comment]
> How about BF16, it should be the same as FP16.

yep. I'll land the code soon.

**Comment by zhyncs** [comment]
Verified throughput and correctness on Llama2 13b Chat, consistent with the base.

**Comment by lzhangzz** [comment]
9% performance drop estimated for prefilling 200k tokens with Llama3-8B.

**Comment by zhyncs** [comment]
> 9% performance drop estimated for prefilling approx 200k tokens with Llama3-8B.
> 
> this PR	v0.4.2
> 69520.48	63873.17
> 69465.04	63672.55
> 69441.23	63659.92
> 69397.99	63625.35
> 69396.67	63574.90

Ok I'll run a detailed timeline analysis later with Llama3-8B. Do you have any suggestions, such as making this feature configurable.

**Pull request closed without merging**
