### PR TITLE
Fix the session_len assignment logic

### PR DESCRIPTION
**Pull request by lvhan028**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
The `scaling_factor` can not be used to determine the context window size

### CODE REVIEW

**Comment by zhyncs** [comment]
Hi @lvhan028 Is it to solve this issue https://github.com/InternLM/lmdeploy/issues/2006

**Review by lzhangzz — APPROVED** [review]

**Comment by lzhangzz** [comment]
This may also solve a few recent issues on OOM.

**Comment by lvhan028** [comment]
> This may also solve a few recent issues on OOM.

Yes.

**Comment by zhyncs** [comment]
Does `rope_scaling_factor` need to be updated in the corresponding documents, such as `docs/en/advance/long_context.md` and `docs/en/inference/turbomind_config.md`

**Comment by lvhan028** [comment]
> Hi @lvhan028 Is it to solve this issue #2006

I haven't investigated #2006 yet. 

> Hi @lvhan028 Is it to solve this issue #2006

I don't think so. Detailed log is necessary for debugging #2006.

**Comment by lvhan028** [comment]
> `rope_scaling_factor`

I think the `long_context.md` is fine. `turbomind_config.md` needs to be updated regardless of this PR.
I will update it in another PR.

**Pull request merged**
