### PR TITLE
Update async_engine.py � checking

### PR DESCRIPTION
**Pull request by Spockhh**
� can appear in anywhere of a block in a stream.

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
The out put of the stream can contain � at other places other than end of the block. To avoid that, need to use operator 'in'.

## Modification

changed if response.endwith('�') to if '�' in response

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
LMDeploy decode token_id one by one. Is it possible that  � character in the middle of decoded text? @AllentDan

**Comment by Spockhh** [comment]
> LMDeploy decode token_id one by one. Is it possible that � character in the middle of decoded text? @AllentDan

Even that's true, the token itself, after decoding, may contains the � middle ?

**Comment by lvhan028** [comment]
No, I think it will not. https://github.com/vllm-project/vllm/blob/0fc280b06cd0cc562281b55b0b70248b119f575b/vllm/transformers_utils/tokenizer.py#L161
 Have you really met a case?

**Comment by AllentDan** [comment]
No, it does not. Only appears at the head and tail of a sequence piece. And in the head means there should be another in the tail of the previous piece.

**Comment by Spockhh** [comment]
> No, I think it will not. https://github.com/vllm-project/vllm/blob/0fc280b06cd0cc562281b55b0b70248b119f575b/vllm/transformers_utils/tokenizer.py#L161 Have you really met a case?

yes, I have met the endwith dosen't work.

**Comment by AllentDan** [comment]
Did you solve the bug by replacing `endswith` with `in`? It's more likely an unexpected token id that the tokenizer can not handle. Rather than cased by incremental decoding.

**Comment by Spockhh** [comment]
> Did you solve the bug by replacing `endswith` with `in`? It's more likely an unexpected token id that the tokenizer can not handle. Rather than cased by incremental decoding.

yes it solved the issue.

**Comment by AllentDan** [comment]
Please give some details for us to reproduce the bug and test the PR.

**Comment by lvhan028** [comment]
Feel free to reopen this PR if a failure case is found

**Pull request closed without merging**
