### PR TITLE
docs: fix Qwen typo

### PR DESCRIPTION
**Pull request by ArtificialZeng**
Qwen not QWen

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily receiving feedbacks. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by lvhan028** [comment]
May also update the chinese version README

**Comment by ArtificialZeng** [comment]
> May also update the chinese version README

you changed it by yourself

**Review by zhyncs — CHANGES_REQUESTED** [review]
Chinese doc needs to be updated too.

**Comment by ArtificialZeng** [comment]
> Chinese doc needs to be updated too.

It's all done by yourself. Can you still accept this pr? I'll be working on this project further. pls.

**Comment by zhyncs** [comment]
Sorry nope. This change is not difficult. What is the reason you are unable to make it here? We need to maintain consistency between the Chinese and English documents.

**Comment by ArtificialZeng** [comment]
> Sorry nope. This change is not difficult. What is the reason you are unable to make it here? We need to maintain consistency between the Chinese and English documents.

Yes! you are absolutely right. 1st, the amendment is easy. But that's all I got. 
it such a great honor for such a big-shot comment on this insignificant fix.
nice talking to you. I wish one day I'll contribute more

**Comment by ArtificialZeng** [comment]
> Sorry nope. This change is not difficult. What is the reason you are unable to make it here? We need to maintain consistency between the Chinese and English documents.

I have made the change as you prescribed. Your tutor and your projects have taught me a lot. Thank you, little bro and little sis.
hope your project will be super famous.

Sincere,
Zeng

**Comment by zhyncs** [comment]
May you also update `docs/zh_cn/supported_models/supported_models.md` and `docs/en/supported_models/supported_models.md` as well? Thank you very much.

**Comment by ArtificialZeng** [comment]
> docs/en/supported_models/supported_models.md

All done! 🎉 You truly are a meticulous and professional expert! Just to let you know, This experience has greatly expanded my knowledge of GitHub, and I appreciate your hard work in maintaining such an impressive project. Looking forward to future collaborations!

**Review by zhyncs — APPROVED** [review]
LGTM

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
