### PR TITLE
use rope_scaling_factor instead to enable Dynamic NTK

### PR DESCRIPTION
**Pull request by jjjjohnson**
Since `use_dynamic_ntk` is no longer used in 0.1.x, update the config key word to `rope_scaling_factor`

### CODE REVIEW

**Review by irexyc — APPROVED** [review]

**Comment by irexyc** [comment]
@jjjjohnson 
shoud also update this line:
https://github.com/InternLM/lmdeploy/blob/5412f142e4653bf12aaf0f3ccf5b42c700d89e4c/lmdeploy/turbomind/deploy/source_model/llama.py#L198

**Comment by jjjjohnson** [comment]
Done

**Comment by lvhan028** [comment]
In qwen's config, 
```
"use_dynamic_ntk": true,
```
In this PR,  `rope_scaling_factor = int(config['use_dynamic_ntk'])` makes `rope_scaling_factor` 1, does it help extrapolation

**Comment by lvhan028** [comment]
`turbomind-2.1` supports this feature.

**Pull request closed without merging**
