### PR TITLE
docs: add BentoLMDeploy in README

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

Recently, BentoML conducted a benchmark https://www.bentoml.com/blog/benchmarking-llm-inference-backends comparison of mainstream LLM inference frameworks in the industry, including an example of how to integrate with bentoml. As bentoml has a large user base overseas, I believe this is beneficial for promoting LMDeploy. Perhaps we may add it in the README. @lvhan028 @lzhangzz 

## Modification

as titled

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by josephrocca** [comment]
I saw that article too and it made me check out LMDeploy. I didn't see the same speedup with "vanilla parameters", but I want to add here that a huge benefit of lmdeploy is its support for both 4 bit KV cache, and prefix caching (which of course aren't set by default and so the Bento benchmark didn't measure it). Together, these two parameters allowed me to get throughput more than 4x(!!!) higher than vLLM and TGI in a VRAM constrained situation (i.e. LLama 2 on two 4090s). Amazing! Kudos to your team. 

Now if only `stop` were fixed and `include_stop_str_in_output` were added (or some other way of determining stop sequence that caused stop), it would be a production-ready competitor and I'd be able to use it :pray: :sweat_smile: 

* https://github.com/InternLM/lmdeploy/issues/1731

**Comment by vody-am** [comment]
@zhyncs you should make a Show HN to hype up `lmdeploy` as well at https://news.ycombinator.com

**Comment by zhyncs** [comment]
> make a Show HN

Great suggestion. We will consider posting a blog introducing LMDeploy on Hacker News and Reddit after TurboMind supports MOE models like Mixtral-8x22B.

By the way, I have been a user of Hacker News for over 6 years. https://github.com/zhyncs/hnbot

**Comment by lvhan028** [comment]
Hi, @zhyncs 
May also update the https://github.com/InternLM/lmdeploy/blob/main/README_zh-CN.md

**Comment by zhyncs** [comment]
> Hi, @zhyncs 
> 
> May also update the https://github.com/InternLM/lmdeploy/blob/main/README_zh-CN.md

ok

**Comment by zhyncs** [comment]
> Hi, @zhyncs May also update the https://github.com/InternLM/lmdeploy/blob/main/README_zh-CN.md

@lvhan028 done

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
