### PR TITLE
Fix convert qwen2 to turbomind

### PR DESCRIPTION
**Pull request by AllentDan**
#1492

### CODE REVIEW

**Review by zhulinJulia24 — APPROVED** [review]
lgtm

**Comment by serser** [comment]
is Qwen-2-72B-instruct supported?

**Comment by AllentDan** [comment]
> is Qwen-2-72B-instruct supported?

I tested Qwen-2-7B-instruct OK.

**Comment by AllentDan** [comment]
> When I am using awq to quantize this model, it errs with nan with the weights of this layer go all nan `model.model.layers[2].mlp.gate_proj.weight`

May refer to https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html#quantization. There are arguments that may influence the calibration. Just try different settings.

**Pull request merged**
