### PR TITLE
ensemble mode of tritonserver

### PR DESCRIPTION
**Pull request by AllentDan**

### CODE REVIEW

**Comment by lvhan028** [comment]
What's the performance of serving after introducing ensemble mode?

**Comment by AllentDan** [comment]
> What's the performance of serving after introducing ensemble mode?

It was tested on a V100. About 10% boost with 16 concurrencies.

**Comment by lvhan028** [comment]
@irexyc please check if this PR affect building prebuilt package?

**Comment by lvhan028** [comment]
Chatbot client should be updated.

**Pull request closed without merging**
