### PR TITLE
fix mixtral and mistral cache_position

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

as titled cc @grimoire @RunningLeon @lvhan028 

tested with `Mixtral-8x7B-Instruct-v0.1` https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1
```bash
python3 -m lmdeploy serve api_server /workdir/Mixtral-8x7B-Instruct-v0.1 --tp 2
```
transformers version: 4.42.3

## Modification

same as https://github.com/InternLM/lmdeploy/pull/1886

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
I just happened to discover the same issue as before with Qwen2 while I was testing the performance of the latest version of PyTorch Engine on `Mixtral-8x7B-Instruct-v0.1`, so I fixed it casually.

**Review by grimoire — DISMISSED** [review]
LGTM

**Comment by RunningLeon** [comment]
hi, @zhyncs if possible, could you check all the models supported by pytorch for transformers==4.42? That would be great.

**Comment by zhyncs** [comment]
Hi @RunningLeon The main bottleneck is in downloading the model. Maybe we can divide the work.

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/blob/main/docs/en/supported_models/supported_models.md cc @RunningLeon @grimoire

**Comment by zhyncs** [comment]
Another way is to add `**kwargs` parameter to the forward of **all PyTorch Engine models**, so that future upgrades of transformers can be compatible with it. Do you have any suggestions? Thanks. @grimoire @RunningLeon

**Comment by grimoire** [comment]
> hi, @zhyncs if possible, could you check all the models supported by pytorch for transformers==4.42? That would be great.

Not necessary.

**Comment by zhyncs** [comment]
> > hi, @zhyncs if possible, could you check all the models supported by pytorch for transformers==4.42? That would be great.
> 
> Not necessary.

ok

**Comment by lvhan028** [comment]
I am using transformers==4.40.0
```
AttributeError: 'Qwen2Config' object has no attribute 'get'
```

**Comment by zhyncs** [comment]
> I got a failure when conducting `pytest tests/test_lmdeploy/test_tokenizer.py`
> 
> ```
> AttributeError: 'Qwen2Config' object has no attribute 'get'
> ```
> 
> The used transformers is 4.40.0.

Let me take a look.

**Comment by lvhan028** [comment]
> > > hi, @zhyncs if possible, could you check all the models supported by pytorch for transformers==4.42? That would be great.
> > 
> > 
> > Not necessary.
> 
> ok

However, I found `cache_position` is introduced for almost each supported model in the latest transformers. @zhyncs @RunningLeon @grimoire

**Comment by zhyncs** [comment]
> I got a failure when conducting `pytest tests/test_lmdeploy/test_tokenizer.py`
> 
> ```
> AttributeError: 'Qwen2Config' object has no attribute 'get'
> ```
> 
> The used transformers is 4.40.0.

ref https://github.com/InternLM/lmdeploy/pull/1952#issuecomment-2214170104

I can run `pytest` locally, which is okay. I suspect there may be a problem with the version of Qwen 2 0.5B Instruct used in the unit test. @zhulinJulia24 cc @lvhan028

**Comment by grimoire** [comment]
> I found cache_position is introduced for almost each supported model in the latest transformers.

We have not update max version yet.
https://github.com/InternLM/lmdeploy/blob/97ba6aa4fa69072466bc527ffbbaffe207876d0d/lmdeploy/pytorch/check_env/__init__.py#L87

Support cache_position in other models can be done in the future.

**Comment by zhyncs** [comment]
> Support cache_position in other models can be done in the future.

@grimoire We can adapt to the rest later, right? I think it’s acceptable. Do you have any suggestions? @lvhan028

**Comment by lvhan028** [comment]
@zhyncs may adapt mistral model, too

**Comment by zhyncs** [comment]
ok

**Comment by zhyncs** [comment]
> @zhyncs may adapt mistral model, too

@grimoire @lvhan028 

v4.41.2
https://github.com/huggingface/transformers/blob/v4.41.2/src/transformers/models/mistral/modeling_mistral.py#L107

v4.42.0
https://github.com/huggingface/transformers/blob/v4.42.0/src/transformers/models/mistral/modeling_mistral.py#L108

https://github.com/InternLM/lmdeploy/blob/af3bdaef2385512511732cdbb77fbd947b3519f9/lmdeploy/pytorch/models/mistral.py#L75-L79

When the transformers version is greater than `v4.42.0`, the forward `seq_len` parameter of MistralRotaryEmbedding is also gone.

The compatibility of the `transformers` library is hard to put into words. I'll take a look and see how to fix it.

**Comment by grimoire** [comment]
https://github.com/InternLM/lmdeploy/blob/c06c7f1f8cc8eea2223259a0e45c919f573156d2/lmdeploy/pytorch/models/internlm2.py#L85 newer transformers models tend to put position ids in rotary embedding.

**Comment by zhyncs** [comment]
> https://github.com/InternLM/lmdeploy/blob/c06c7f1f8cc8eea2223259a0e45c919f573156d2/lmdeploy/pytorch/models/internlm2.py#L85
> 
> newer transformers models tend to put position ids in rotary embedding.

ok

**Comment by zhyncs** [comment]
Hi @grimoire 

What's the purpose of the value_states transpose?
https://github.com/InternLM/lmdeploy/blob/c06c7f1f8cc8eea2223259a0e45c919f573156d2/lmdeploy/pytorch/models/internlm2.py#L91-L92

**Comment by zhyncs** [comment]
done @lvhan028 @grimoire @RunningLeon

**Comment by grimoire** [comment]
> What's the purpose of the value_states transpose?

legacy code. Can be ignored.

**Review by RunningLeon — APPROVED** [review]
LGTM

**Comment by zhyncs** [comment]
cc @grimoire

**Review by grimoire — APPROVED** [review]

**Pull request merged**
