### PR TITLE
docs add debug turbomind guide

### PR DESCRIPTION
**Pull request by zhyncs**
## Motivation

add debug Turbomind guide

## Modification

add debug Turbomind guide in `advance` section

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a dependency on downstream projects of a newer version, this PR should be tested with all supported versions of downstream projects.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by zhyncs** [comment]
Hi @lvhan028 @lzhangzz @irexyc @AllentDan May you help review this pr? Thanks.

**Comment by lvhan028** [comment]
I followed the guide, but still got failure when performing `gdb python3`

**Comment by zhyncs** [comment]
> I followed the guide, but still got failure when performing `gdb python3`

Please paste the detailed log.

**Comment by lvhan028** [comment]
```
(lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ rpm -qa | grep glibc
glibc-common-2.17-326.el7_9.x86_64
glibc-debuginfo-2.17-326.el7_9.x86_64
glibc-devel-2.17-326.el7_9.x86_64
glibc-debuginfo-common-2.17-326.el7_9.x86_64
glibc-headers-2.17-326.el7_9.x86_64
glibc-2.17-326.el7_9.x86_64
(lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ which python3
/nvme/lvhan/miniconda3/envs/lmdeploy/bin/python3
(lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ rpm -qa | grep python3
python3-setuptools-39.2.0-10.el7.noarch
python3-rpm-macros-3-34.el7.noarch
python3-3.6.8-19.el7_9.x86_64
python3-pip-9.0.3-8.el7.noarch
python3-libs-3.6.8-19.el7_9.x86_64
python3-devel-3.6.8-19.el7_9.x86_64
python3-debuginfo-3.6.8-19.el7_9.x86_64
python3-rpm-generators-6-2.el7.noarch
```

**Comment by zhyncs** [comment]
> ```
> (lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ rpm -qa | grep glibc
> glibc-common-2.17-326.el7_9.x86_64
> glibc-debuginfo-2.17-326.el7_9.x86_64
> glibc-devel-2.17-326.el7_9.x86_64
> glibc-debuginfo-common-2.17-326.el7_9.x86_64
> glibc-headers-2.17-326.el7_9.x86_64
> glibc-2.17-326.el7_9.x86_64
> (lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ which python3
> /nvme/lvhan/miniconda3/envs/lmdeploy/bin/python3
> (lmdeploy) [lvhan@SH-IDC1-10-140-24-142 lmdeploy]$ rpm -qa | grep python3
> python3-setuptools-39.2.0-10.el7.noarch
> python3-rpm-macros-3-34.el7.noarch
> python3-3.6.8-19.el7_9.x86_64
> python3-pip-9.0.3-8.el7.noarch
> python3-libs-3.6.8-19.el7_9.x86_64
> python3-devel-3.6.8-19.el7_9.x86_64
> python3-debuginfo-3.6.8-19.el7_9.x86_64
> python3-rpm-generators-6-2.el7.noarch
> ```

You're actually using python 3.8, and the debuginfo installation is python 3.6.8, so the problem is caused by an inconsistency between the two.

**Comment by lvhan028** [comment]
I see. The default python version in CentOS 7 is 3.6
But LMDeploy requires python 3.8+
So, how to install python3.8+ debug info on centos 7?

**Comment by zhyncs** [comment]
> I see. The default python version in CentOS 7 is 3.6 But LMDeploy requires python 3.8+ So, how to install python3.8+ debug info on centos 7?

I built LMDeploy from source with Python 3.9.16.

```
-DPYTHON_EXECUTABLE=/usr/local/bin/python3
```

```
[username@hostname lmdeploy]# /usr/local/bin/python3 --version
Python 3.9.16
```

When I use `gdb python3`, it invokes Python 3.6.8 and shows `Reading symbols from python3...`.

```
[username@hostname lmdeploy]# gdb python3
GNU gdb (GDB) Red Hat Enterprise Linux 9.2-10.el7
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(gdb) 
```

```
[username@hostname lmdeploy]# which gdb
/opt/rh/devtoolset-10/root/usr/bin/gdb
```

```
[username@hostname lmdeploy]# ls lmdeploy/lib | grep turbomind | grep python | grep so
_turbomind.cpython-39-x86_64-linux-gnu.so
```

gdb is installed with
```
sudo yum install devtoolset-10 -y
```

Therefore, I believe that using a higher version of Python to compile LMDeploy and installing debuginfo with Python 3.6 is fine. The key is to use Python 3.6 with `gdb python3`. During actual debugging, the higher version of Python's so file is still called.
Maybe you can try the `gdb` installed with `sudo yum install devtoolset-10 -y`.

**Comment by lvhan028** [comment]
May add `Upgrade gdb` section both in en & zh_cn documents
```shell
sudo yum install devtoolset-10 -y
echo "source scl_source enable devtoolset-10" >> ~/.bashrc
source ~/.bashrc
```

**Comment by zhyncs** [comment]
> May add `Upgrade gdb` section both in en & zh_cn documents
> 
> ```shell
> sudo yum install devtoolset-10 -y
> echo "source scl_source enable devtoolset-10" >> ~/.bashrc
> source ~/.bashrc
> ```

ok

**Comment by zhyncs** [comment]
> May add `Upgrade gdb` section both in en & zh_cn documents
> 
> ```shell
> sudo yum install devtoolset-10 -y
> echo "source scl_source enable devtoolset-10" >> ~/.bashrc
> source ~/.bashrc
> ```

done

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
