### PR TITLE
Upgrade gradio

### PR DESCRIPTION
**Pull request by AllentDan**
Please note for gradio>4. The proxy policy was changed. You may get `httpcore.ConnectTimeout: timed out` of `_do_normal_analytics_request` function.

### CODE REVIEW

**Comment by lvhan028** [comment]
```
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/workspace/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/workspace/lmdeploy/lmdeploy/cli/serve.py", line 259, in gradio
    run(args.model_path_or_server,
  File "/workspace/lmdeploy/lmdeploy/serve/gradio/app.py", line 58, in run
    run_local(model_path_or_server,
  File "/workspace/lmdeploy/lmdeploy/serve/gradio/turbomind_coupled.py", line 232, in run_local
    demo.queue(
  File "/opt/py38/lib/python3.8/site-packages/gradio/blocks.py", line 2420, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.
```

**Comment by AllentDan** [comment]
I could not reproduce the error. May refer to https://github.com/chenfei-wu/TaskMatrix/issues/250

**Comment by lvhan028** [comment]
> I could not reproduce the error. May refer to [chenfei-wu/TaskMatrix#250](https://github.com/chenfei-wu/TaskMatrix/issues/250)

I tried, but still got failure. My gradio version is 4.37.2

**Comment by AllentDan** [comment]
How about try `lmdeploy serve gradio model_path --share`

**Comment by lvhan028** [comment]
> How about you try `lmdeploy serve gradio model_path --share`

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/py38/lib/python3.8/site-packages/gradio/analytics.py", line 70, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "/opt/py38/lib/python3.8/site-packages/gradio/analytics.py", line 131, in get_local_ip_address
    ip_address = httpx.get(
  File "/opt/py38/lib/python3.8/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/opt/py38/lib/python3.8/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/opt/py38/lib/python3.8/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/py38/lib/python3.8/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/opt/py38/lib/python3.8/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/py38/lib/python3.8/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/py38/lib/python3.8/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/py38/lib/python3.8/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/py38/lib/python3.8/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out
```

**Comment by AllentDan** [comment]
> Please note for gradio>4. The proxy policy was changed. You may get `httpcore.ConnectTimeout: timed out` of `_do_normal_analytics_request` function.

Yes, but it was introduced by gradio>4 and proxy. It does not influence usage. It can't be reproduced in my local machine.

**Comment by AllentDan** [comment]
> Please note for gradio>4. The proxy policy was changed. You may get `httpcore.ConnectTimeout: timed out` of `_do_normal_analytics_request` function.

I've mentioned this.

**Comment by lvhan028** [comment]
> > Please note for gradio>4. The proxy policy was changed. You may get `httpcore.ConnectTimeout: timed out` of `_do_normal_analytics_request` function.
> 
> I've mentioned this, but it was introduced by gradio>4 and proxy. It does not influence usage. It can't be reproduced in my local machine.

Try the docker image

**Comment by AllentDan** [comment]
> Try the docker image

Tested OK except the log info `httpx.ConnectTimeout: timed out`.

**Comment by lvhan028** [comment]
Can you share the way to launch the server?
It is 100% reproducible at my side

**Comment by lvhan028** [comment]
> Can you share the way to launch the server? It is 100% reproducible at my side

Now I understand that 
```
httpx.ConnectTimeout: timed out happened but didn't affect the usage.
```

**Review by lvhan028 — APPROVED** [review]

**Pull request merged**
