### PR TITLE
lazy import accelerate.init_empty_weights for vl async engine

### PR DESCRIPTION
**Pull request by irexyc**
## Motivation

accelerate import lmdeploy.pipeline

### CODE REVIEW

**Review by RunningLeon — APPROVED** [review]
LGTM

**Review by grimoire — APPROVED** [review]

**Comment by lvhan028** [comment]
@irexyc could you help test the import time of lmdeploy in the internstudio with this PR?

**Comment by irexyc** [comment]
With this pr, the cost time of `lmdeploy -h` command has been improved from 49s to 19s.

**Comment by lvhan028** [comment]
> > could you help test the import time of lmdeploy in the internstudio with this PR?
> 
> With this pr, the cost time of `lmdeploy -h` command has been improved from 49s to 19s.

Can it be improved more?

**Comment by irexyc** [comment]
Import torch takes a long time. In my test, the loading time vary from 10s to 49s

**Pull request merged**
