### PR TITLE
adjust app.py dependency

### PR DESCRIPTION
**Pull request by AllentDan**
#234

### CODE REVIEW

**Review by lvhan028 — APPROVED** [review]
LGTM

**Comment by grimoire** [comment]
Why would serving import tm if tm is not required?

**Comment by AllentDan** [comment]
> Why would serving import tm if tm is not required?

Serving with gradio supports two ways:
1. serving with tritonserver
2. serving with turbomind directly

**Comment by grimoire** [comment]
Why not import turbomind in the function call that serving turbomind?

**Comment by AllentDan** [comment]
Lets say. If I want to import `Tokenizer` or other modules from turbomind while turbomind was not build. The error will be triggered.

**Comment by grimoire** [comment]
All module inside turbomind should be depended on pythonbind, if it is not, move it out.

**Review by grimoire — APPROVED** [review]

**Pull request merged**
